easy_admin:
    site_name: 'Digitalendar Admin'
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Event
        - App\Entity\User
        - App\Entity\City
        - App\Entity\Participant
        - App\Entity\Langage
